const DATA = [
  {
    _id: 1,
    name: 'iPhone 6s 128Gb Gold',
    group_id: 2,
    discount: true,
    img: 'iphone-6s-gold.jpg',
    price: 1121,
  },
  {
    _id: 2,
    name: 'iPhone 6s 128Gb Rose',
    group_id: 2,
    discount: false,
    img: 'iphone-6s-rose.jpg',
    price: 1389,
  },
  {
    _id: 3,
    name: 'iPhone 6s 128Gb Silver',
    group_id: 2,
    discount: false,
    img: 'iphone-6s-silver.jpg',
    price: 1499,
  },
  {
    _id: 4,
    name: 'iPhone 6s 128Gb Space',
    group_id: 2,
    discount: false,
    img: 'iphone-6s-gray.jpg',
    price: 1200,
  },
  {
    _id: 5,
    name: 'iPhone 6s Plus 128Gb Gold',
    group_id: 3,
    discount: true,
    img: 'iphone-6s-plus-gold.jpg',
    price: 1121,
  },
  {
    _id: 6,
    name: 'iPhone 6s Plus 128Gb Rose',
    group_id: 3,
    discount: false,
    img: 'iphone-6s-plus-rose.jpg',
    price: 1530,
  },
  {
    _id: 7,
    name: 'iPhone 6s Plus 128Gb Silver',
    group_id: 3,
    discount: false,
    img: 'iphone-6s-plus-silver.jpg',
    price: 1530,
  },
  {
    _id: 8,
    name: 'iPhone 6s Plus 128Gb Space',
    group_id: 3,
    discount: false,
    img: 'iphone-6s-plus-gray.jpg',
    price: 1530,
  },
  {
    _id: 9,
    name: 'iPhone 6 16Gb Gold',
    group_id: 4,
    discount: true,
    img: 'iphone-6-gold.jpg',
    price: 848,
  },
  {
    _id: 10,
    name: 'iPhone 6 16Gb Silver',
    group_id: 4,
    discount: false,
    img: 'iphone-6-silver.jpg',
    price: 848,
  },
  {
    _id: 11,
    name: 'iPhone 6 16Gb Space',
    group_id: 4,
    discount: false,
    img: 'iphone-6-gray.jpg',
    price: 848,
  },
  {
    _id: 12,
    name: 'iPhone 6 Plus 64Gb Gold',
    group_id: 5,
    discount: true,
    img: 'iphone-6-plus-gold.jpg',
    price: 1039,
  },
  {
    _id: 13,
    name: 'iPhone 6 Plus 64Gb Silver',
    group_id: 5,
    discount: false,
    img: 'iphone-6-plus-silver.jpg',
    price: 1039,
  },
  {
    _id: 14,
    name: 'iPhone 6 Plus 64Gb Space',
    group_id: 5,
    discount: false,
    img: 'iphone-6-plus-gray.jpg',
    price: 1039,
  },
  {
    _id: 15,
    name: 'iPhone 5s 16Gb Gold A1530',
    group_id: 6,
    discount: true,
    img: 'iphone-5s-gold.jpg',
    price: 590,
  },
  {
    _id: 16,
    name: 'iPhone 5s 16Gb Silver A1530',
    group_id: 6,
    discount: false,
    img: 'iphone-5s-silver.jpg',
    price: 590,
  },
  {
    _id: 17,
    name: 'iPhone 5s 16Gb Space',
    group_id: 6,
    discount: false,
    img: 'iphone-5s-gray.jpg',
    price: 590,
  },
  {
    _id: 18,
    name: 'iPhone 7 Plus 256Gb Black',
    group_id: 1,
    discount: true,
    img: 'iphone-7-plus-black.jpg',
    price: 1990,
  },
  {
    _id: 19,
    name: 'iPhone 7 Plus 256Gb Gold',
    group_id: 1,
    discount: false,
    img: 'iphone-7-plus-gold.jpg',
    price: 1990,
  },
  {
    _id: 20,
    name: 'iPhone 7 Plus 256Gb JetBlack',
    group_id: 1,
    discount: false,
    img: 'iphone-7-plus-jetblack.jpg',
    price: 1990,
  },
  {
    _id: 21,
    name: 'iPhone 7 Plus 256Gb Rose',
    group_id: 1,
    discount: false,
    img: 'iphone-7-plus-rose.jpg',
    price: 1990,
  }
];